import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@repo/shared/styles/globals.css";
import { QueryClientProvider } from "@repo/shared";
import { StoreProvider } from "@/providers/mobx-store-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryClientProvider>
          <StoreProvider>
            <main className="mx-auto max-w-md">{children}</main>
          </StoreProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
