import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@repo/shared/styles/globals.css";
import { QueryClientProvider } from "@repo/shared";
import RecoilWrapper from "@/components/RecoilWrapper";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <RecoilWrapper>
          <QueryClientProvider>
            <main className="mx-auto max-w-md">{children}</main>
          </QueryClientProvider>
        </RecoilWrapper>
      </body>
    </html>
  );
}
